// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGTp9qpiZ3Nq-JyyxYuPeZzdW1u8xBvjg',
    appId: '1:888441402002:web:db5dbc7d9e6dc935ab2c4b',
    messagingSenderId: '888441402002',
    projectId: 'all-features-project',
    authDomain: 'all-features-project.firebaseapp.com',
    storageBucket: 'all-features-project.firebasestorage.app',
    measurementId: 'G-KJNDL21Y3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr8Cy_bgWXhmRO-JiVmjVeE-d8qToboP8',
    appId: '1:888441402002:android:4697d8889ab6b26eab2c4b',
    messagingSenderId: '888441402002',
    projectId: 'all-features-project',
    storageBucket: 'all-features-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7YdxWUCvnAdx4o3vkvKBcD3ncqQcSktA',
    appId: '1:888441402002:ios:a27dcba41e7078aeab2c4b',
    messagingSenderId: '888441402002',
    projectId: 'all-features-project',
    storageBucket: 'all-features-project.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7YdxWUCvnAdx4o3vkvKBcD3ncqQcSktA',
    appId: '1:888441402002:ios:a27dcba41e7078aeab2c4b',
    messagingSenderId: '888441402002',
    projectId: 'all-features-project',
    storageBucket: 'all-features-project.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGTp9qpiZ3Nq-JyyxYuPeZzdW1u8xBvjg',
    appId: '1:888441402002:web:1258a1683959a838ab2c4b',
    messagingSenderId: '888441402002',
    projectId: 'all-features-project',
    authDomain: 'all-features-project.firebaseapp.com',
    storageBucket: 'all-features-project.firebasestorage.app',
    measurementId: 'G-MF0FW5LCZ6',
  );
}
